# Generated by Django 5.0.3 on 2024-03-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.BooleanField()),
                ('botao', models.BooleanField()),
                ('liga_robo', models.BooleanField()),
                ('reset_contador', models.BooleanField()),
                ('valor_contagem', models.IntegerField()),
            ],
        ),
    ]
